<%@ page contentType="text/html; charset=utf-8"%>
<input id="info_id" type="hidden" class="width200" value="0" />
<input id="cat_id" type="hidden" class="width200" value="0" />
<input id="from_id" type="hidden" class="width200" value="0" />
<input id="content_url" type="hidden" class="width200" value="0" />
<input id="wf_id" type="hidden" class="width200" value="0" />
<input id="step_id" type="hidden" class="width200" value="0" />
<input id="final_status" type="hidden" class="width200" value="0" />
<input id="hits" type="hidden" class="width200" value="0" />
<input id="day_hits" type="hidden" class="width200" value="0" />
<input id="week_hits" type="hidden" class="width200" value="0" />
<input id="month_hits" type="hidden" class="width200" value="0" />
<input id="lasthit_dtime" type="hidden" class="width200" value="0" />
<input id="comment_num" type="hidden" class="width200" value="0" />
<input id="input_user" type="hidden" class="width200" value="0" />
<input id="input_dtime" type="hidden" class="width200" value="0" />
<input id="modify_user" type="hidden" class="width200" value="0" />
<input id="modify_dtime" type="hidden" class="width200" value="0" />
<input id="opt_dtime" type="hidden" class="width200" value="0" />
<input id="is_auto_up" type="hidden" class="width200" value="0" />
<input id="is_auto_down" type="hidden" class="width200" value="0" />
<input id="down_dtime" type="hidden" class="width200" value="0" />
<input id="is_host" type="hidden" class="width200" value="0" />
<input id="title_hashkey" type="hidden" class="width200" value="0" />
<input id="site_id" type="hidden" class="width200" value="0" />
<input id="i_ver" type="hidden" class="width200" value="0" />
<input id="page_count" type="hidden" class="width200" value="0" />
<input id="prepage_wcount" type="hidden" class="width200" value="0" />
<input id="word_count" type="hidden" class="width200" value="0" />